version: '3.4'

services: 
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./MonitoredApplication/promconfig.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml


  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
      
  monitoredapplication:
    image: ${DOCKER_REGISTRY-}monitoredapplication
    build:
      context: .
      dockerfile: MonitoredApplication/Dockerfile
   
  