# create configmap k8s from text file
# kubectl create configmap prometheus-cfgmap --from-file=MonitoredApplication/promconfig.yml --dry-run -o yaml > promconfig-cfgmap.yaml
apiVersion: v1
data:
  prometheus.yml: "\uFEFF\x67\x6C\x6F\x62\x61\x6C\x3A\r\n\x20\x20\x73\x63\x72\x61\x70\x65\x5F\x69\x6E\x74\x65\x72\x76\x61\x6C\x3A\x20\x31\x35\x73\r\n\r\n\x73\x63\x72\x61\x70\x65\x5F\x63\x6F\x6E\x66\x69\x67\x73\x3A\r\n\x20\x20\x2D\x20\x6A\x6F\x62\x5F\x6E\x61\x6D\x65\x3A\x20\x27\x6D\x6F\x6E\x69\x74\x6F\x72\x65\x64\x61\x70\x70\x5F\x6A\x6F\x62\x27\r\n\x20\x20\x20\x20\x73\x63\x72\x61\x70\x65\x5F\x69\x6E\x74\x65\x72\x76\x61\x6C\x3A\x20\x35\x73\x20\r\n\x20\x20\x20\x20\x73\x74\x61\x74\x69\x63\x5F\x63\x6F\x6E\x66\x69\x67\x73\x3A\r\n\x20\x20\x20\x20\x20\x20\x2D\x20\x74\x61\x72\x67\x65\x74\x73\x3A\x20\x5B\x27\x6D\x6F\x6E\x69\x74\x6F\x72\x65\x64\x61\x70\x70\x6C\x69\x63\x61\x74\x69\x6F\x6E\x3A\x38\x30\x27\x5D\r\n\x20\x20\x20\x20\x74\x6C\x73\x5F\x63\x6F\x6E\x66\x69\x67\x3A\r\n\x20\x20\x20\x20\x20\x20\x69\x6E\x73\x65\x63\x75\x72\x65\x5F\x73\x6B\x69\x70\x5F\x76\x65\x72\x69\x66\x79\x3A\x20\x74\x72\x75\x65\x20\x20\x23\x20\x54\x68\x69\x73\x20\x69\x73\x20\x74\x68\x65\x20\x6B\x65\x79"
kind: ConfigMap
metadata:
  name: prometheus-cfgmap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
spec:
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-cfg-vol
          mountPath: /etc/prometheus
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: prometheus-cfg-vol
        configMap:
          name: prometheus-cfgmap
---
# Prometheus Service
apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
spec:
  type: LoadBalancer
  selector:
    app: prometheus
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090